EWPP-1165: Add support for update-related parameters in site install command.
openeuropa/task-runner pull request #153
Opened 2021-07-22 13:23 UTC by sergepavle

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2021-07-27 14:01 UTC, 22Alexandra approved these changes, later dismissed

2021-07-28 09:02 UTC, 22Alexandra submitted a review, later dismissed

2021-07-29 09:26 UTC, nagyad requested changes

2021-07-29 09:26 UTC, nagyad commented on config/runner.yml
> +    # By settings this to NULL we will disable update status module option
By settings this to NULL, we will disable update the status module option

2021-07-29 09:26 UTC, nagyad commented on config/runner.yml
> +    # By settings this to NULL we will disable update status emails option
By settings this to NULL, we will disable update the status emails option

2021-07-30 08:05 UTC, nagyad approved these changes, later dismissed

2021-07-30 08:48 UTC, 22Alexandra approved these changes, later dismissed

2021-08-03 08:13 UTC, 22Alexandra approved these changes, later dismissed

2021-10-25 09:23 UTC, brummbar requested changes

2021-11-05 14:09 UTC, brummbar commented on src/Tasks/Drush/Drush.php
> +    public function setUpdateStatusModule($updateStatusModule)
I made a mistake here in the suggested name, i forgot "update". I also noticed the other methods don't have set, let's drop it: `enableUpdateStatusModuleOnInstall`. Same for other method.

2021-12-02 17:02 UTC, brummbar requested changes

2023-06-21 10:52 UTC, imanoleguskiza requested changes

2023-06-21 10:52 UTC, imanoleguskiza commented on composer.json
> +        "We need to use the 1.x version of grasmash/expander so that null values are treated the same way they were treated until release 2.0.0-alpha2 ."
This comment needs to be changed/removed

2023-08-09 12:37 UTC, brummbar requested changes

2023-08-09 12:37 UTC, brummbar commented on composer.json
> +        "grasmash/expander": ">=3"
Shoudln't we just ^3?

2025-06-11 13:52 UTC, closed without merging