OEL-3318: Prepare for php8.3
openeuropa/task-runner pull request #173
Opened 2024-11-29 13:41 UTC by drishu

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2024-12-03 11:46 UTC, AaronGilMartinez requested changes

2024-12-03 11:46 UTC, AaronGilMartinez commented on composer.json
> +        "openeuropa/code-review-library": "^1.0.0-alpha1",
Set minimum stability to alpha again

2024-12-09 10:02 UTC, sergepavle commented
Looks like now we can cleanup 'config.allow-plugins' with this:
`        "allow-plugins": {
            "dealerdirect/phpcodesniffer-composer-installer": true,
            "phpro/grumphp-shim": true
        }`

2024-12-09 10:35 UTC, sergepavle commented on composer.json
>          "slevomat/coding-standard": "^7.0 || ^8.0"
Do we still need this package? I didn't find anywhere in composer.lock other packages that used this.

2024-12-09 12:03 UTC, sergepavle approved these changes, later dismissed

2024-12-11 09:14 UTC, AaronGilMartinez requested changes

2024-12-11 09:14 UTC, AaronGilMartinez commented on composer.json
> -            "cweagans/composer-patches": true,
There is some leftover configuration for patches in extra

2024-12-11 09:59 UTC, AaronGilMartinez approved these changes

2024-12-11 10:11 UTC, sergepavle approved these changes

2024-12-11 10:13 UTC, merged